/**
 * Three Sisters Stories - Content Loader
 * Loads content from manifest.json (generated by build.py)
 */

// Load content for a sister's page
async function loadSisterContent(sisterName) {
  try {
    const response = await fetch(`content/manifest.json?v=${Date.now()}`);
    const manifest = await response.json();
    const data = manifest[sisterName];

    if (!data) {
      console.error(`No content found for ${sisterName}`);
      showEmptyStates();
      return;
    }

    renderVideos(data.videos || []);
    renderBooksRead(data.booksRead || []);
    renderBooksWantToRead(data.booksWantToRead || []);
    renderJournal(data.journal || []);
    renderDrawings(data.drawings || [], sisterName);

  } catch (error) {
    console.error('Error loading content:', error);
    showEmptyStates();
  }
}

function showEmptyStates() {
  renderVideos([]);
  renderBooksRead([]);
  renderBooksWantToRead([]);
  renderJournal([]);
  renderDrawings([]);
}

// Render videos section
function renderVideos(videos) {
  const container = document.getElementById('videos-grid');
  if (!container) return;

  if (videos.length === 0) {
    container.innerHTML = `
      <div class="empty-state">
        <span class="icon">🎥</span>
        <p>Videos coming soon!</p>
      </div>
    `;
    return;
  }

  container.innerHTML = videos.map(video => `
    <div class="video-container">
      <div class="video-wrapper">
        <iframe
          src="https://www.youtube-nocookie.com/embed/${video.id}"
          title="${video.title || ''}"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen>
        </iframe>
      </div>
      <p class="video-title">${video.title || ''}</p>
      ${video.date ? `<p class="video-date">${video.date}</p>` : ''}
    </div>
  `).join('');
}

// Render books I have read
function renderBooksRead(books) {
  const container = document.getElementById('books-read-list');
  if (!container) return;

  if (books.length === 0) {
    container.innerHTML = `
      <div class="empty-state">
        <span class="icon">📖</span>
        <p>No books yet!</p>
      </div>
    `;
    return;
  }

  const emojis = ['📕', '📗', '📘', '📙', '📓', '📔'];
  container.innerHTML = books.map((book, i) => `
    <div class="book-item">
      <span class="book-emoji">${emojis[i % emojis.length]}</span>
      <div class="book-info">
        <h3>${book.title}</h3>
        ${book.author ? `<p class="author">by ${book.author}</p>` : ''}
        ${book.date_started ? `<p class="date-started">Started: ${book.date_started}</p>` : ''}
        ${book.thoughts ? `<p class="thoughts">"${book.thoughts}"</p>` : ''}
      </div>
    </div>
  `).join('');
}

// Render books I want to read
function renderBooksWantToRead(books) {
  const container = document.getElementById('books-want-list');
  if (!container) return;

  if (books.length === 0) {
    container.innerHTML = `
      <div class="empty-state">
        <span class="icon">📚</span>
        <p>Add some books you want to read!</p>
      </div>
    `;
    return;
  }

  container.innerHTML = books.map(book => `
    <div class="book-item book-want">
      <span class="book-emoji">📖</span>
      <div class="book-info">
        <h3>${book.title}</h3>
        ${book.author ? `<p class="author">by ${book.author}</p>` : ''}
        ${book.notes ? `<p class="notes">${book.notes}</p>` : ''}
      </div>
    </div>
  `).join('');
}

// Render journal entries
function renderJournal(entries) {
  const container = document.getElementById('journal-entries');
  if (!container) return;

  if (entries.length === 0) {
    container.innerHTML = `
      <div class="empty-state">
        <span class="icon">✏️</span>
        <p>Journal entries coming soon!</p>
      </div>
    `;
    return;
  }

  container.innerHTML = entries.map(entry => `
    <div class="journal-entry">
      <p class="date">${entry.date}${entry.title ? ` - ${entry.title}` : ''}</p>
      <div class="content">${formatText(entry.content)}</div>
    </div>
  `).join('');
}

// Render drawings gallery
function renderDrawings(drawings, sisterName) {
  const container = document.getElementById('drawings-gallery');
  if (!container) return;

  if (!drawings || drawings.length === 0) {
    container.innerHTML = `
      <div class="empty-state">
        <span class="icon">🖍️</span>
        <p>Drawings coming soon!</p>
      </div>
    `;
    return;
  }

  container.innerHTML = drawings.map(drawing => `
    <div class="drawing-item">
      ${drawing.image
        ? `<img src="images/${sisterName}/${drawing.image}" alt="${drawing.title}">`
        : `<div class="drawing-placeholder">${drawing.emoji || '🎨'}</div>`
      }
      <p class="title">${drawing.title}</p>
    </div>
  `).join('');
}

// Simple text formatter
function formatText(text) {
  if (!text) return '';
  return text
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');
}

// Smooth scroll for anchor links
document.addEventListener('DOMContentLoaded', () => {
  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function(e) {
      e.preventDefault();
      const target = document.querySelector(this.getAttribute('href'));
      if (target) {
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });
});
